services:
  - type: web
    name: listingspark-ai-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: 8000
      - key: HOST
        value: 0.0.0.0
    autoDeploy: true
